spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:42000"
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
